package domain.prenda;

public enum Categoria {
    PARTE_SUPERIOR,
    PARTE_SUPERIOR_ARRIBA,
    PARTE_SUPERIOR_MEDIO,
    PARTE_SUPERIOR_ABAJO,
    CALZADO,
    PARTE_INFERIOR,
    ACCESORIO_MANOS,
    ACCESORIO,
    ACCESORIO_CUELLO,
    ACCESORIO_CABEZA,
    ACCESORIO_PIES,
    NINGUNO
}
